/* Generated by Yosys 0.57+263 (git sha1 637665c9d, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:8.1-24.10" *)
module SOC(CLK, RESET, LEDS, RXD, TXD);
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:9.17-9.20" *)
  input CLK;
  wire CLK;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:10.17-10.22" *)
  input RESET;
  wire RESET;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:11.23-11.27" *)
  output [4:0] LEDS;
  wire [4:0] LEDS;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:12.17-12.20" *)
  input RXD;
  wire RXD;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:13.17-13.20" *)
  output TXD;
  wire TXD;
  wire CLK_IBUF_I_O;
  (* unused_bits = "0" *)
  wire RESET_IBUF_I_O;
  (* unused_bits = "0" *)
  wire RXD_IBUF_I_O;
  wire TXD_OBUF_O_I;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:18.14-18.19" *)
  wire [4:0] count;
  wire count_DFF_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFF_Q_1_D_ALU_SUM_COUT;
  wire count_DFF_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFF_Q_2_D_ALU_SUM_COUT;
  wire count_DFF_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFF_Q_3_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire count_DFF_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFF_Q_3_D_ALU_SUM_COUT;
  wire count_DFF_Q_4_D;
  wire count_DFF_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire count_DFF_Q_D_ALU_SUM_COUT;
  wire count_DFF_Q_D_ALU_SUM_I3;
  (* keep = 32'd1 *)
  IBUF CLK_IBUF_I (
    .I(CLK),
    .O(CLK_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O (
    .I(count[4]),
    .O(LEDS[4])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_1 (
    .I(count[3]),
    .O(LEDS[3])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_2 (
    .I(count[2]),
    .O(LEDS[2])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_3 (
    .I(count[1]),
    .O(LEDS[1])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_4 (
    .I(count[0]),
    .O(LEDS[0])
  );
  (* keep = 32'd1 *)
  IBUF RESET_IBUF_I (
    .I(RESET),
    .O(RESET_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  IBUF RXD_IBUF_I (
    .I(RXD),
    .O(RXD_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF TXD_OBUF_O (
    .I(TXD_OBUF_O_I),
    .O(TXD)
  );
  GND TXD_OBUF_O_I_GND_G (
    .G(TXD_OBUF_O_I)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:19.4-21.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF count_DFF_Q (
    .CLK(CLK_IBUF_I_O),
    .D(count_DFF_Q_D),
    .Q(count[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:19.4-21.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF count_DFF_Q_1 (
    .CLK(CLK_IBUF_I_O),
    .D(count_DFF_Q_1_D),
    .Q(count[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFF_Q_1_D_ALU_SUM (
    .CIN(count_DFF_Q_2_D_ALU_SUM_COUT),
    .COUT(count_DFF_Q_1_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[3]),
    .I3(count_DFF_Q_D_ALU_SUM_I3),
    .SUM(count_DFF_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:19.4-21.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF count_DFF_Q_2 (
    .CLK(CLK_IBUF_I_O),
    .D(count_DFF_Q_2_D),
    .Q(count[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFF_Q_2_D_ALU_SUM (
    .CIN(count_DFF_Q_3_D_ALU_SUM_COUT),
    .COUT(count_DFF_Q_2_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[2]),
    .I3(count_DFF_Q_D_ALU_SUM_I3),
    .SUM(count_DFF_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:19.4-21.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF count_DFF_Q_3 (
    .CLK(CLK_IBUF_I_O),
    .D(count_DFF_Q_3_D),
    .Q(count[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFF_Q_3_D_ALU_SUM (
    .CIN(count_DFF_Q_3_D_ALU_SUM_CIN),
    .COUT(count_DFF_Q_3_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[1]),
    .I3(count_DFF_Q_D_ALU_SUM_I3),
    .SUM(count_DFF_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFF_Q_3_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(TXD_OBUF_O_I),
    .COUT(count_DFF_Q_3_D_ALU_SUM_CIN),
    .I0(count_DFF_Q_D_ALU_SUM_I3),
    .I1(count[0]),
    .I3(count_DFF_Q_D_ALU_SUM_I3),
    .SUM(count_DFF_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:19.4-21.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF count_DFF_Q_4 (
    .CLK(CLK_IBUF_I_O),
    .D(count_DFF_Q_4_D),
    .Q(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_DFF_Q_4_D_LUT1_F (
    .F(count_DFF_Q_4_D),
    .I0(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step1.v:20.16-20.25|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFF_Q_D_ALU_SUM (
    .CIN(count_DFF_Q_1_D_ALU_SUM_COUT),
    .COUT(count_DFF_Q_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[4]),
    .I3(count_DFF_Q_D_ALU_SUM_I3),
    .SUM(count_DFF_Q_D)
  );
  VCC count_DFF_Q_D_ALU_SUM_I3_VCC_V (
    .V(count_DFF_Q_D_ALU_SUM_I3)
  );
endmodule
