/* Generated by Yosys 0.57+263 (git sha1 637665c9d, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:11.1-42.10" *)
module SOC(CLK, RESET, LEDS, RXD, TXD);
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:12.12-12.15" *)
  input CLK;
  wire CLK;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:13.12-13.17" *)
  input RESET;
  wire RESET;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:14.18-14.22" *)
  output [4:0] LEDS;
  wire [4:0] LEDS;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:15.12-15.15" *)
  input RXD;
  wire RXD;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:16.12-16.15" *)
  output TXD;
  wire TXD;
  (* hdlname = "CW CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:44.11-44.14" *)
  wire \CW.CLK ;
  (* hdlname = "CW RESET" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:45.11-45.16" *)
  wire \CW.RESET ;
  (* hdlname = "CW clk" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:46.11-46.14" *)
  wire \CW.clk ;
  wire \CW.clk_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire \CW.clk_DFF_Q_D_ALU_SUM_COUT ;
  (* hdlname = "CW genblk1.slow_CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:70.20-70.28" *)
  wire [21:0] \CW.genblk1.slow_CLK ;
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ;
  (* unused_bits = "0" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_20_D ;
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ;
  (* unused_bits = "0" *)
  wire RXD_IBUF_I_O;
  wire TXD_OBUF_O_I;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:19.9-19.12" *)
  wire clk;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:23.14-23.19" *)
  wire [4:0] count;
  wire count_DFFR_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFFR_Q_1_D_ALU_SUM_COUT;
  wire count_DFFR_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFFR_Q_2_D_ALU_SUM_COUT;
  wire count_DFFR_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFFR_Q_3_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire count_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire count_DFFR_Q_3_D_ALU_SUM_COUT;
  wire count_DFFR_Q_4_D;
  wire count_DFFR_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire count_DFFR_Q_D_ALU_SUM_COUT;
  wire count_DFFR_Q_D_ALU_SUM_I3;
  (* keep = 32'd1 *)
  IBUF \CW.CLK_IBUF_O  (
    .I(CLK),
    .O(\CW.CLK )
  );
  (* keep = 32'd1 *)
  IBUF \CW.RESET_IBUF_O  (
    .I(RESET),
    .O(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.clk_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.clk_DFF_Q_D ),
    .Q(\CW.clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.clk_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .COUT(\CW.clk_DFF_Q_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.clk ),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.clk_DFF_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_D ),
    .Q(\CW.genblk1.slow_CLK [20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_1  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_1_D ),
    .Q(\CW.genblk1.slow_CLK [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_10  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_10_D ),
    .Q(\CW.genblk1.slow_CLK [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [10]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_10_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_11  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_11_D ),
    .Q(\CW.genblk1.slow_CLK [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [9]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_11_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_12  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_12_D ),
    .Q(\CW.genblk1.slow_CLK [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [8]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_12_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_13  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_13_D ),
    .Q(\CW.genblk1.slow_CLK [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [7]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_13_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_14  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_14_D ),
    .Q(\CW.genblk1.slow_CLK [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [6]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_14_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_15  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_15_D ),
    .Q(\CW.genblk1.slow_CLK [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [5]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_15_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_16  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_16_D ),
    .Q(\CW.genblk1.slow_CLK [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [4]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_16_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_17  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_17_D ),
    .Q(\CW.genblk1.slow_CLK [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [3]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_17_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_18  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_18_D ),
    .Q(\CW.genblk1.slow_CLK [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [2]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_18_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_19  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_19_D ),
    .Q(\CW.genblk1.slow_CLK [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [1]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT  (
    .CIN(TXD_OBUF_O_I),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .I0(count_DFFR_Q_D_ALU_SUM_I3),
    .I1(\CW.genblk1.slow_CLK [0]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [19]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_2  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_2_D ),
    .Q(\CW.genblk1.slow_CLK [18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_20  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .Q(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) \CW.genblk1.slow_CLK_DFF_Q_20_D_LUT1_F  (
    .F(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .I0(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [18]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_3  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_3_D ),
    .Q(\CW.genblk1.slow_CLK [17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [17]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_4  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_4_D ),
    .Q(\CW.genblk1.slow_CLK [16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [16]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_5  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_5_D ),
    .Q(\CW.genblk1.slow_CLK [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [15]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_6  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_6_D ),
    .Q(\CW.genblk1.slow_CLK [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [14]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_6_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_7  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_7_D ),
    .Q(\CW.genblk1.slow_CLK [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [13]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_7_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_8  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_8_D ),
    .Q(\CW.genblk1.slow_CLK [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [12]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_8_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_9  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_9_D ),
    .Q(\CW.genblk1.slow_CLK [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [11]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_9_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .I0(TXD_OBUF_O_I),
    .I1(\CW.genblk1.slow_CLK [20]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_D )
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O (
    .I(count[4]),
    .O(LEDS[4])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_1 (
    .I(count[3]),
    .O(LEDS[3])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_2 (
    .I(count[2]),
    .O(LEDS[2])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_3 (
    .I(count[1]),
    .O(LEDS[1])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_4 (
    .I(count[0]),
    .O(LEDS[0])
  );
  (* keep = 32'd1 *)
  IBUF RXD_IBUF_I (
    .I(RXD),
    .O(RXD_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF TXD_OBUF_O (
    .I(TXD_OBUF_O_I),
    .O(TXD)
  );
  GND TXD_OBUF_O_I_GND_G (
    .G(TXD_OBUF_O_I)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:24.4-26.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR count_DFFR_Q (
    .CLK(\CW.clk ),
    .D(count_DFFR_Q_D),
    .Q(count[4]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:24.4-26.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR count_DFFR_Q_1 (
    .CLK(\CW.clk ),
    .D(count_DFFR_Q_1_D),
    .Q(count[3]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFFR_Q_1_D_ALU_SUM (
    .CIN(count_DFFR_Q_2_D_ALU_SUM_COUT),
    .COUT(count_DFFR_Q_1_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[3]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(count_DFFR_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:24.4-26.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR count_DFFR_Q_2 (
    .CLK(\CW.clk ),
    .D(count_DFFR_Q_2_D),
    .Q(count[2]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFFR_Q_2_D_ALU_SUM (
    .CIN(count_DFFR_Q_3_D_ALU_SUM_COUT),
    .COUT(count_DFFR_Q_2_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[2]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(count_DFFR_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:24.4-26.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR count_DFFR_Q_3 (
    .CLK(\CW.clk ),
    .D(count_DFFR_Q_3_D),
    .Q(count[1]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFFR_Q_3_D_ALU_SUM (
    .CIN(count_DFFR_Q_3_D_ALU_SUM_CIN),
    .COUT(count_DFFR_Q_3_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[1]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(count_DFFR_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(TXD_OBUF_O_I),
    .COUT(count_DFFR_Q_3_D_ALU_SUM_CIN),
    .I0(count_DFFR_Q_D_ALU_SUM_I3),
    .I1(count[0]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(count_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:24.4-26.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR count_DFFR_Q_4 (
    .CLK(\CW.clk ),
    .D(count_DFFR_Q_4_D),
    .Q(count[0]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_DFFR_Q_4_D_LUT1_F (
    .F(count_DFFR_Q_4_D),
    .I0(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step2.v:25.30-25.39|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) count_DFFR_Q_D_ALU_SUM (
    .CIN(count_DFFR_Q_1_D_ALU_SUM_COUT),
    .COUT(count_DFFR_Q_D_ALU_SUM_COUT),
    .I0(TXD_OBUF_O_I),
    .I1(count[4]),
    .I3(count_DFFR_Q_D_ALU_SUM_I3),
    .SUM(count_DFFR_Q_D)
  );
  VCC count_DFFR_Q_D_ALU_SUM_I3_VCC_V (
    .V(count_DFFR_Q_D_ALU_SUM_I3)
  );
  assign \CW.genblk1.slow_CLK [21] = \CW.clk ;
  assign clk = \CW.clk ;
endmodule
