/* Generated by Yosys 0.57+263 (git sha1 637665c9d, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:13.1-142.10" *)
module SOC(CLK, RESET, LEDS, RXD, TXD);
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:14.12-14.15" *)
  input CLK;
  wire CLK;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:15.12-15.17" *)
  input RESET;
  wire RESET;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:16.18-16.22" *)
  output [4:0] LEDS;
  wire [4:0] LEDS;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:17.12-17.15" *)
  input RXD;
  wire RXD;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:18.12-18.15" *)
  output TXD;
  wire TXD;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:80.16-80.20" *)
  wire [31:0] Bimm;
  (* hdlname = "CW CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:44.11-44.14" *)
  wire \CW.CLK ;
  (* hdlname = "CW RESET" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:45.11-45.16" *)
  wire \CW.RESET ;
  (* hdlname = "CW clk" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:46.11-46.14" *)
  wire \CW.clk ;
  wire \CW.clk_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire \CW.clk_DFF_Q_D_ALU_SUM_COUT ;
  (* hdlname = "CW genblk1.slow_CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:70.20-70.28" *)
  wire [21:0] \CW.genblk1.slow_CLK ;
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ;
  (* unused_bits = "0" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_20_D ;
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:78.16-78.20" *)
  wire [31:0] Iimm;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:81.16-81.20" *)
  wire [31:0] Jimm;
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/brams_map.v:113.14-113.16" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \MEM.0.0_DO ;
  (* force_downto = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] \MEM.0.0_DO_1 ;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:25.15-25.17" *)
  wire [31:0] PC;
  wire PC_DFFR_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_1_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_2_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_3_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_4_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_4_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_5_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_5_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_6_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_6_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire PC_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_6_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_7_D;
  wire PC_DFFR_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire PC_DFFR_Q_D_ALU_SUM_COUT;
  (* unused_bits = "0" *)
  wire RXD_IBUF_I_O;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:79.16-79.20" *)
  wire [31:0] Simm;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:77.16-77.20" *)
  wire [31:0] Uimm;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:21.9-21.12" *)
  wire clk;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:89.15-89.21" *)
  wire [2:0] funct3;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:90.15-90.21" *)
  wire [6:0] funct7;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:26.15-26.20" *)
  wire [31:0] instr;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:66.9-66.17" *)
  wire isALUimm;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:65.9-65.17" *)
  wire isALUreg;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:72.9-72.15" *)
  wire isLoad;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:74.9-74.17" *)
  wire isSYSTEM;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:73.9-73.16" *)
  wire isStore;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:86.15-86.19" *)
  wire [4:0] rdId;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:84.15-84.20" *)
  wire [4:0] rs1Id;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:85.15-85.20" *)
  wire [4:0] rs2Id;
  (* keep = 32'd1 *)
  IBUF \CW.CLK_IBUF_O  (
    .I(CLK),
    .O(\CW.CLK )
  );
  (* keep = 32'd1 *)
  IBUF \CW.RESET_IBUF_O  (
    .I(RESET),
    .O(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.clk_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.clk_DFF_Q_D ),
    .Q(\CW.clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.clk_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .COUT(\CW.clk_DFF_Q_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.clk ),
    .I3(instr[1]),
    .SUM(\CW.clk_DFF_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_D ),
    .Q(\CW.genblk1.slow_CLK [20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_1  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_1_D ),
    .Q(\CW.genblk1.slow_CLK [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_10  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_10_D ),
    .Q(\CW.genblk1.slow_CLK [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [10]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_10_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_11  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_11_D ),
    .Q(\CW.genblk1.slow_CLK [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [9]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_11_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_12  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_12_D ),
    .Q(\CW.genblk1.slow_CLK [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [8]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_12_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_13  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_13_D ),
    .Q(\CW.genblk1.slow_CLK [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [7]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_13_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_14  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_14_D ),
    .Q(\CW.genblk1.slow_CLK [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [6]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_14_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_15  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_15_D ),
    .Q(\CW.genblk1.slow_CLK [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [5]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_15_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_16  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_16_D ),
    .Q(\CW.genblk1.slow_CLK [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [4]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_16_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_17  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_17_D ),
    .Q(\CW.genblk1.slow_CLK [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [3]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_17_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_18  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_18_D ),
    .Q(\CW.genblk1.slow_CLK [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [2]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_18_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_19  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_19_D ),
    .Q(\CW.genblk1.slow_CLK [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [1]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT  (
    .CIN(isSYSTEM),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .I0(instr[1]),
    .I1(\CW.genblk1.slow_CLK [0]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [19]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_2  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_2_D ),
    .Q(\CW.genblk1.slow_CLK [18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_20  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .Q(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) \CW.genblk1.slow_CLK_DFF_Q_20_D_LUT1_F  (
    .F(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .I0(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [18]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_3  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_3_D ),
    .Q(\CW.genblk1.slow_CLK [17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [17]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_4  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_4_D ),
    .Q(\CW.genblk1.slow_CLK [16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [16]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_5  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_5_D ),
    .Q(\CW.genblk1.slow_CLK [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [15]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_6  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_6_D ),
    .Q(\CW.genblk1.slow_CLK [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [14]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_6_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_7  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_7_D ),
    .Q(\CW.genblk1.slow_CLK [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [13]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_7_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_8  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_8_D ),
    .Q(\CW.genblk1.slow_CLK [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [12]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_8_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_9  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_9_D ),
    .Q(\CW.genblk1.slow_CLK [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [11]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_9_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .I0(isSYSTEM),
    .I1(\CW.genblk1.slow_CLK [20]),
    .I3(instr[1]),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_D )
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O (
    .I(PC[0]),
    .O(LEDS[4])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_1 (
    .I(isALUreg),
    .O(LEDS[3])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_2 (
    .I(isALUimm),
    .O(LEDS[2])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_3 (
    .I(isStore),
    .O(LEDS[1])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_4 (
    .I(isLoad),
    .O(LEDS[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/brams_map.v:124.4-134.3" *)
  SP #(
    .BIT_WIDTH(32'd1),
    .BLK_SEL(3'h0),
    .INIT_RAM_00(256'h000000000000000000000000000000000000000000000000000000000000009f),
    .INIT_RAM_01(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_02(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_03(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_04(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_05(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_06(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_07(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_08(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_09(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_10(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_11(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_12(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_13(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_14(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_15(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_16(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_17(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_18(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_19(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_20(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_21(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_22(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_23(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_24(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_25(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_26(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_27(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_28(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_29(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_30(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_31(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_32(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_33(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_34(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_35(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_36(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_37(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_38(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_39(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .READ_MODE(1'h0),
    .RESET_MODE("ASYNC"),
    .WRITE_MODE(32'd2)
  ) \MEM.0.0  (
    .AD({ isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, PC[7:0] }),
    .BLKSEL({ isSYSTEM, isSYSTEM, isSYSTEM }),
    .CE(instr[1]),
    .CLK(\CW.clk ),
    .DI({ isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM }),
    .DO({ \MEM.0.0_DO [31:1], \MEM.0.0_DO_1 [0] }),
    .OCE(instr[1]),
    .RESET(isSYSTEM),
    .WRE(isSYSTEM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR \MEM.0.0_DO_1_DFFR_Q  (
    .CLK(\CW.clk ),
    .D(instr[1]),
    .Q(\MEM.0.0_DO_1 [2]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_D),
    .Q(PC[7]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_1 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_1_D),
    .Q(PC[6]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_1_D_ALU_SUM (
    .CIN(PC_DFFR_Q_2_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_1_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[6]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_2 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_2_D),
    .Q(PC[5]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_2_D_ALU_SUM (
    .CIN(PC_DFFR_Q_3_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_2_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[5]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_3 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_3_D),
    .Q(PC[4]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_3_D_ALU_SUM (
    .CIN(PC_DFFR_Q_4_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_3_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[4]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_4 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_4_D),
    .Q(PC[3]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_4_D_ALU_SUM (
    .CIN(PC_DFFR_Q_5_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_4_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[3]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_4_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_5 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_5_D),
    .Q(PC[2]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_5_D_ALU_SUM (
    .CIN(PC_DFFR_Q_6_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_5_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[2]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_5_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_6 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_6_D),
    .Q(PC[1]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_6_D_ALU_SUM (
    .CIN(PC_DFFR_Q_6_D_ALU_SUM_CIN),
    .COUT(PC_DFFR_Q_6_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[1]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_6_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(isSYSTEM),
    .COUT(PC_DFFR_Q_6_D_ALU_SUM_CIN),
    .I0(instr[1]),
    .I1(PC[0]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_7 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_7_D),
    .Q(PC[0]),
    .RESET(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) PC_DFFR_Q_7_D_LUT1_F (
    .F(PC_DFFR_Q_7_D),
    .I0(PC[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:98.9-98.13|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_D_ALU_SUM (
    .CIN(PC_DFFR_Q_1_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_D_ALU_SUM_COUT),
    .I0(isSYSTEM),
    .I1(PC[7]),
    .I3(instr[1]),
    .SUM(PC_DFFR_Q_D)
  );
  (* keep = 32'd1 *)
  IBUF RXD_IBUF_I (
    .I(RXD),
    .O(RXD_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF TXD_OBUF_O (
    .I(isSYSTEM),
    .O(TXD)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:92.4-103.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:55.7-55.57" *)
  DFFS instr_DFFS_Q (
    .CLK(\CW.clk ),
    .D(isSYSTEM),
    .Q(instr[5]),
    .SET(\CW.RESET )
  );
  VCC instr_VCC_V (
    .V(instr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h23)
  ) isALUimm_LUT3_F (
    .F(isALUimm),
    .I0(\MEM.0.0_DO_1 [0]),
    .I1(instr[5]),
    .I2(\MEM.0.0_DO_1 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h8c)
  ) isALUreg_LUT3_F (
    .F(isALUreg),
    .I0(\MEM.0.0_DO_1 [0]),
    .I1(instr[5]),
    .I2(\MEM.0.0_DO_1 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h10)
  ) isLoad_LUT3_F (
    .F(isLoad),
    .I0(\MEM.0.0_DO_1 [0]),
    .I1(instr[5]),
    .I2(\MEM.0.0_DO_1 [2])
  );
  GND isSYSTEM_GND_G (
    .G(isSYSTEM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h40)
  ) isStore_LUT3_F (
    .F(isStore),
    .I0(\MEM.0.0_DO_1 [0]),
    .I1(instr[5]),
    .I2(\MEM.0.0_DO_1 [2])
  );
  assign \MEM.0.0_DO_1 [1] = instr[5];
  assign \MEM.0.0_DO [0] = \MEM.0.0_DO_1 [0];
  assign Bimm = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign \CW.genblk1.slow_CLK [21] = \CW.clk ;
  assign Iimm = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign Jimm = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign PC[31:8] = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign Simm = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign Uimm = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign clk = \CW.clk ;
  assign funct3 = { isSYSTEM, isSYSTEM, isSYSTEM };
  assign funct7 = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign { instr[31:6], instr[4:2], instr[0] } = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, instr[1] };
  assign rdId = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign rs1Id = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
  assign rs2Id = { isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM, isSYSTEM };
endmodule
