/* Generated by Yosys 0.57+263 (git sha1 637665c9d, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:11.1-70.10" *)
module SOC(CLK, RESET, LEDS, RXD, TXD);
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:12.12-12.15" *)
  input CLK;
  wire CLK;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:13.12-13.17" *)
  input RESET;
  wire RESET;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:14.18-14.22" *)
  output [4:0] LEDS;
  wire [4:0] LEDS;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:15.12-15.15" *)
  input RXD;
  wire RXD;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:16.12-16.15" *)
  output TXD;
  wire TXD;
  (* hdlname = "CW CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:44.11-44.14" *)
  wire \CW.CLK ;
  (* hdlname = "CW RESET" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:45.11-45.16" *)
  wire \CW.RESET ;
  wire \CW.RESET_LUT3_I0_F ;
  (* force_downto = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] \CW.RESET_LUT3_I0_I2 ;
  (* hdlname = "CW clk" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:46.11-46.14" *)
  wire \CW.clk ;
  wire \CW.clk_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire \CW.clk_DFF_Q_D_ALU_SUM_COUT ;
  (* hdlname = "CW genblk1.slow_CLK" *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:70.20-70.28" *)
  wire [21:0] \CW.genblk1.slow_CLK ;
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ;
  (* unused_bits = "0" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_20_D ;
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ;
  wire \CW.genblk1.slow_CLK_DFF_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ;
  wire \MEM.0.0_AD ;
  wire \MEM.0.0_CE ;
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/brams_map.v:139.14-139.16" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35" *)
  wire [35:0] \MEM.0.0_DO ;
  (* unused_bits = "5 6 7 8" *)
  wire [8:0] \MEM.0.0_DO_1 ;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:22.14-22.16" *)
  wire [4:0] PC;
  wire PC_DFFR_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_1_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_2_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_3_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire PC_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire PC_DFFR_Q_3_D_ALU_SUM_COUT;
  wire PC_DFFR_Q_4_D;
  wire PC_DFFR_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire PC_DFFR_Q_D_ALU_SUM_COUT;
  (* unused_bits = "0" *)
  wire RXD_IBUF_I_O;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:19.9-19.12" *)
  wire clk;
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:48.14-48.18" *)
  wire [4:0] leds;
  (* keep = 32'd1 *)
  IBUF \CW.CLK_IBUF_O  (
    .I(CLK),
    .O(\CW.CLK )
  );
  (* keep = 32'd1 *)
  IBUF \CW.RESET_IBUF_O  (
    .I(RESET),
    .O(\CW.RESET )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hba)
  ) \CW.RESET_LUT3_I0  (
    .F(\CW.RESET_LUT3_I0_F ),
    .I0(\CW.RESET ),
    .I1(PC[3]),
    .I2(\CW.RESET_LUT3_I0_I2 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0008)
  ) \CW.RESET_LUT3_I0_I2_LUT4_F  (
    .F(\CW.RESET_LUT3_I0_I2 [2]),
    .I0(PC[4]),
    .I1(PC[2]),
    .I2(PC[1]),
    .I3(PC[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.clk_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.clk_DFF_Q_D ),
    .Q(\CW.clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.clk_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .COUT(\CW.clk_DFF_Q_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.clk ),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.clk_DFF_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_D ),
    .Q(\CW.genblk1.slow_CLK [20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_1  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_1_D ),
    .Q(\CW.genblk1.slow_CLK [19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_10  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_10_D ),
    .Q(\CW.genblk1.slow_CLK [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [10]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_10_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_11  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_11_D ),
    .Q(\CW.genblk1.slow_CLK [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_11_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [9]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_11_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_12  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_12_D ),
    .Q(\CW.genblk1.slow_CLK [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_12_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [8]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_12_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_13  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_13_D ),
    .Q(\CW.genblk1.slow_CLK [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_13_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [7]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_13_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_14  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_14_D ),
    .Q(\CW.genblk1.slow_CLK [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_14_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [6]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_14_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_15  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_15_D ),
    .Q(\CW.genblk1.slow_CLK [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_15_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [5]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_15_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_16  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_16_D ),
    .Q(\CW.genblk1.slow_CLK [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_16_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [4]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_16_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_17  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_17_D ),
    .Q(\CW.genblk1.slow_CLK [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_17_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [3]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_17_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_18  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_18_D ),
    .Q(\CW.genblk1.slow_CLK [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_18_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [2]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_18_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_19  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_19_D ),
    .Q(\CW.genblk1.slow_CLK [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [1]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT  (
    .CIN(\MEM.0.0_AD ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN ),
    .I0(\MEM.0.0_CE ),
    .I1(\CW.genblk1.slow_CLK [0]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_19_D_ALU_SUM_CIN_ALU_COUT_SUM )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [19]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_2  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_2_D ),
    .Q(\CW.genblk1.slow_CLK [18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_20  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .Q(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) \CW.genblk1.slow_CLK_DFF_Q_20_D_LUT1_F  (
    .F(\CW.genblk1.slow_CLK_DFF_Q_20_D ),
    .I0(\CW.genblk1.slow_CLK [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_2_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [18]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_3  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_3_D ),
    .Q(\CW.genblk1.slow_CLK [17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_3_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [17]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_4  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_4_D ),
    .Q(\CW.genblk1.slow_CLK [16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_4_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [16]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_5  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_5_D ),
    .Q(\CW.genblk1.slow_CLK [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_5_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [15]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_6  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_6_D ),
    .Q(\CW.genblk1.slow_CLK [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_6_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [14]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_6_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_7  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_7_D ),
    .Q(\CW.genblk1.slow_CLK [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_7_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [13]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_7_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_8  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_8_D ),
    .Q(\CW.genblk1.slow_CLK [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_8_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [12]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_8_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:71.3-73.6|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \CW.genblk1.slow_CLK_DFF_Q_9  (
    .CLK(\CW.CLK ),
    .D(\CW.genblk1.slow_CLK_DFF_Q_9_D ),
    .Q(\CW.genblk1.slow_CLK [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_10_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_9_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [11]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_9_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/clockworks.v:72.18-72.30|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) \CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM  (
    .CIN(\CW.genblk1.slow_CLK_DFF_Q_1_D_ALU_SUM_COUT ),
    .COUT(\CW.genblk1.slow_CLK_DFF_Q_D_ALU_SUM_COUT ),
    .I0(\MEM.0.0_AD ),
    .I1(\CW.genblk1.slow_CLK [20]),
    .I3(\MEM.0.0_CE ),
    .SUM(\CW.genblk1.slow_CLK_DFF_Q_D )
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O (
    .I(\MEM.0.0_DO [4]),
    .O(LEDS[4])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_1 (
    .I(\MEM.0.0_DO [3]),
    .O(LEDS[3])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_2 (
    .I(\MEM.0.0_DO [2]),
    .O(LEDS[2])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_3 (
    .I(\MEM.0.0_DO [1]),
    .O(LEDS[1])
  );
  (* keep = 32'd1 *)
  OBUF LEDS_OBUF_O_4 (
    .I(\MEM.0.0_DO [0]),
    .O(LEDS[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/brams_map.v:150.4-160.3" *)
  SPX9 #(
    .BIT_WIDTH(32'd9),
    .BLK_SEL(3'h0),
    .INIT_RAM_00(288'h00000000000000000000000000008060381e0f8783a1c0d0643014090442008020080200),
    .INIT_RAM_01(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_02(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_03(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_04(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_05(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_06(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_07(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_08(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_09(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_10(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_11(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_12(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_13(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_14(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_15(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_16(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_17(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_18(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_19(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_20(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_21(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_22(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_23(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_24(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_25(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_26(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_27(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_28(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_29(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_30(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_31(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_32(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_33(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_34(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_35(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_36(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_37(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_38(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_39(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .READ_MODE(1'h0),
    .RESET_MODE("ASYNC"),
    .WRITE_MODE(32'd2)
  ) \MEM.0.0  (
    .AD({ \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , PC, \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD  }),
    .BLKSEL({ \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD  }),
    .CE(\MEM.0.0_CE ),
    .CLK(\CW.clk ),
    .DI({ \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD , \MEM.0.0_AD  }),
    .DO(\MEM.0.0_DO ),
    .OCE(\MEM.0.0_CE ),
    .RESET(\MEM.0.0_AD ),
    .WRE(\MEM.0.0_AD )
  );
  GND \MEM.0.0_AD_GND_G  (
    .G(\MEM.0.0_AD )
  );
  VCC \MEM.0.0_CE_VCC_V  (
    .V(\MEM.0.0_CE )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:55.4-57.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_D),
    .Q(PC[4]),
    .RESET(\CW.RESET_LUT3_I0_F )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:55.4-57.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_1 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_1_D),
    .Q(PC[3]),
    .RESET(\CW.RESET_LUT3_I0_F )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_1_D_ALU_SUM (
    .CIN(PC_DFFR_Q_2_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_1_D_ALU_SUM_COUT),
    .I0(\MEM.0.0_AD ),
    .I1(PC[3]),
    .I3(\MEM.0.0_CE ),
    .SUM(PC_DFFR_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:55.4-57.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_2 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_2_D),
    .Q(PC[2]),
    .RESET(\CW.RESET_LUT3_I0_F )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_2_D_ALU_SUM (
    .CIN(PC_DFFR_Q_3_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_2_D_ALU_SUM_COUT),
    .I0(\MEM.0.0_AD ),
    .I1(PC[2]),
    .I3(\MEM.0.0_CE ),
    .SUM(PC_DFFR_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:55.4-57.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_3 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_3_D),
    .Q(PC[1]),
    .RESET(\CW.RESET_LUT3_I0_F )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_3_D_ALU_SUM (
    .CIN(PC_DFFR_Q_3_D_ALU_SUM_CIN),
    .COUT(PC_DFFR_Q_3_D_ALU_SUM_COUT),
    .I0(\MEM.0.0_AD ),
    .I1(PC[1]),
    .I3(\MEM.0.0_CE ),
    .SUM(PC_DFFR_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(\MEM.0.0_AD ),
    .COUT(PC_DFFR_Q_3_D_ALU_SUM_CIN),
    .I0(\MEM.0.0_CE ),
    .I1(PC[0]),
    .I3(\MEM.0.0_CE ),
    .SUM(PC_DFFR_Q_3_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:55.4-57.7|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR PC_DFFR_Q_4 (
    .CLK(\CW.clk ),
    .D(PC_DFFR_Q_4_D),
    .Q(PC[0]),
    .RESET(\CW.RESET_LUT3_I0_F )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) PC_DFFR_Q_4_D_LUT1_F (
    .F(PC_DFFR_Q_4_D),
    .I0(PC[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/mnt/c/Workspace/FPGA/learn-fpga_GOWIN/FemtoRV/TUTORIALS/FROM_BLINKER_TO_RISCV/step4.v:56.40-56.44|/home/fpolo/oss-cad-suite/lib/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) PC_DFFR_Q_D_ALU_SUM (
    .CIN(PC_DFFR_Q_1_D_ALU_SUM_COUT),
    .COUT(PC_DFFR_Q_D_ALU_SUM_COUT),
    .I0(\MEM.0.0_AD ),
    .I1(PC[4]),
    .I3(\MEM.0.0_CE ),
    .SUM(PC_DFFR_Q_D)
  );
  (* keep = 32'd1 *)
  IBUF RXD_IBUF_I (
    .I(RXD),
    .O(RXD_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF TXD_OBUF_O (
    .I(\MEM.0.0_AD ),
    .O(TXD)
  );
  assign \CW.RESET_LUT3_I0_I2 [1:0] = { PC[3], \CW.RESET  };
  assign \CW.genblk1.slow_CLK [21] = \CW.clk ;
  assign \MEM.0.0_DO_1  = \MEM.0.0_DO [8:0];
  assign clk = \CW.clk ;
  assign leds = \MEM.0.0_DO [4:0];
endmodule
